version: "3.9"
services:
  backend:
    build:
      context: ./backend/backend
    container_name: backend-prod
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Mongo__ConnectionString=mongodb://mongo:27017
      - Mongo__Database=mydatabase
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
    container_name: frontend-prod
    ports:
      - "80:80"
    depends_on:
      - backend

  mongo:
    image: mongo:7.0
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
